name: Java CI with GitHub Actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v3

      - name: Java 18 설치 
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'

      - name: Maven 캐싱 설정 (빌드 속도 개선)
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-

      - name: Maven 빌드 실행
        run: mvn clean package

      - name: TMDB API 성능 비교 실행
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }} 
        run: java -cp target/ci-demo-1.0-SNAPSHOT.jar com.mycompany.ci.demo.TMDBApiDemo
