name: Java CI with GitHub Actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v3

      - name: Java 설치
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Maven 캐싱 설정
        uses: actions/cache@v3
        with:
          path: ~/.m2 
          key: maven-${{ hashFiles('**/pom.xml') }} 
          restore-keys: maven-

      - name: 프로젝트 빌드
        run: mvn clean package
